name: refresh stats
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install cloc
      run: brew install cloc

    - name: git clone
      run: python main.py ${{ github.actor }}

    - name: generate imgs
      run: |
        python create_lang_img.py
        python create_overview_img.py ${{ github.actor }}

    - name: push imgs
      run: |
        git config --global user.name bot
        git add languages.svg overview.svg
        git commit -m 'bot update' || echo
        git push
